services:
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=etl_user
      - POSTGRES_PASSWORD=etl_pass
      - POSTGRES_DB=movies
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
